### ISSUE TITLE
Error in Query Building on German System

### ISSUE THREAD

**Issue by nufer** [LeanKit/LeanKit.IntegrationService#2]
in IntegrationService.Targets.JIRA.Jira
````
jqlQuery = string.Format(project.Query, queryAsOfDate.ToString("yyyy/MM/dd hh:mm"));
````

results in a formated DateTime String like "yyyy.MM.dd hh:mm" if executed on a german System (which results in an exception in Jira 
````
Date value '1.2.2015 12:55' for field 'updated' is invalid. Valid formats include: 'yyyy/MM/dd HH:mm', 'yyyy-MM-dd HH:mm', 'yyyy/MM/dd', 'yyyy-MM-dd', or a period format e.g. '-5d', '4w 2d'.
````

queryAsOfDate.ToString("yyyy-MM-dd hh:mm") could be used instead, which is not translated into a culter relevant format

**Comment by reverentgeek** [comment]
Hi,

Thanks for reporting this. It appears there are more date formatting issues when running under non-US cultural settings than just the JIRA query. I am reviewing our code for these other issues, and hope to get back to you with a fix soon.

Thanks!

**Comment by reverentgeek** [comment]
Hi,

Can you download the [latest version](https://support.leankit.com/hc/en-us/articles/204413753-LeanKit-Integration-Service-Download)? This should resolve any issues querying and updating JIRA and LeanKit when running on Windows with German culture.

**Comment by nufer** [comment]
i tried it... does not work.

If I start a Query with this syntax, this is the result...



what solves my problem is just to change to the "-" notification:

````

jqlQuery =

string.Format(project.Query, queryAsOfDate.ToString("yyyy-MM-dd 
hh:mm"));
````

------ Originalnachricht ------
Von: "David Neal" <notifications@github.com>
An: "LeanKit/LeanKit.IntegrationService" 
<LeanKit.IntegrationService@noreply.github.com>
Cc: "nufer" <dominik@nufer.org>
Gesendet: 09.02.2015 23:36:00
Betreff: Re: [LeanKit.IntegrationService] Error in Query Building on 
German System (#2)

**Comment by reverentgeek** [comment]
Can you try downloading and running [this updated version](http://1drv.ms/1MaKuJK) and let me know if that resolves the issue?

**Comment by nufer** [comment]
Now, it works! Thank you
